name: CI Build and Test

# Triggers the workflow on push or pull request events for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks out your repository code
    - uses: actions/checkout@v4
    
    # Sets up a specific version of Node.js (change to your project's requirement)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Installs the project dependencies
    - name: Install dependencies
      run: npm ci

    # Runs the tests (change the command if needed)
    - name: Run tests
      run: npm test

    # An optional step to build the project (e.g., for production assets)
    - name: Build project
      run: npm run build
